// danger-data.mjs — curated gallery of genuinely dangerous / destructive shell
// commands. Each entry is a real command that cmdxray's risk engine flags; the
// annotated breakdown + warnings on each page are generated live from the SAME
// engine the tool ships (scripts/gen-pages.mjs), so nothing here is hand-faked.
// The prose fields below (what/why/safer) are hand-written and reviewed for
// accuracy. High-intent, high-search-volume, genuinely educational — NOT a
// how-to: every page leads with the danger and a safe alternative.

export const DANGERS = [
  {
    slug: "rm-rf-slash",
    cmd: "rm -rf --no-preserve-root /",
    label: "rm -rf --no-preserve-root /",
    tagline: "Erase the entire filesystem from the root down",
    what: "Recursively and forcibly deletes every file starting at the root directory (/). The --no-preserve-root flag exists only to switch off the safety interlock that modern rm uses to refuse this exact command.",
    why: "This wipes the whole system — the OS, your data, everything mounted under / — without a single confirmation prompt. There is no undo. On many setups it will keep deleting until the shell itself disappears.",
    safer: "Never disable --no-preserve-root. Delete a specific, absolute path you have typed out in full (e.g. rm -rf /home/me/old-project), and consider `rm -rI` which asks once before removing a lot of files.",
  },
  {
    slug: "rm-rf-home",
    cmd: "rm -rf $HOME/",
    label: "rm -rf $HOME",
    tagline: "Delete your entire home directory, no prompt",
    what: "Recursively force-deletes everything under your home directory — documents, config, SSH keys, projects.",
    why: "A single stray variable or trailing slash turns routine cleanup into total data loss. If $HOME is empty or unset, `rm -rf $HOME/` can degrade toward `rm -rf /`.",
    safer: "Delete named subpaths, not $HOME itself. Quote and expand variables carefully, and test the target first with `ls -d -- \"$HOME/thing\"` before deleting.",
  },
  {
    slug: "fork-bomb",
    cmd: ":(){ :|:& };:",
    label: ":(){ :|:& };: (fork bomb)",
    tagline: "Spawn processes until the machine grinds to a halt",
    what: "Defines a shell function named ':' that calls itself twice and pipes the two copies together in the background, then invokes it. Each call doubles the number of running processes.",
    why: "Process count explodes exponentially in milliseconds, exhausting the process table and memory until the system becomes unresponsive and often needs a hard reboot.",
    safer: "Never run it outside a throwaway VM. Protect real machines with a per-user process cap via `ulimit -u` or an /etc/security/limits.conf nproc limit.",
  },
  {
    slug: "curl-pipe-sudo-bash",
    cmd: "curl -fsSL https://example.com/install.sh | sudo bash",
    label: "curl … | sudo bash",
    tagline: "Run unread code from the internet, as root",
    what: "Downloads a script over the network and pipes it straight into a root shell, executing whatever the server returns without ever writing it to disk or showing it to you.",
    why: "You are trusting the server, its TLS, and its DNS completely — a compromised or swapped payload runs with full superuser privileges. The content can differ from what a browser shows, and there is no review step.",
    safer: "Download first, read it, then run: `curl -fsSL URL -o install.sh`, inspect install.sh, and only then `sudo bash install.sh`. Prefer signed packages from your distro's repository where possible.",
  },
  {
    slug: "wget-pipe-sh",
    cmd: "wget -qO- https://example.com/setup.sh | sh",
    label: "wget … | sh",
    tagline: "Same as curl|bash — pipe a remote script into a shell",
    what: "Fetches a remote script quietly to stdout and pipes it directly into sh, running it unseen.",
    why: "Identical risk profile to curl | bash: arbitrary remote code executes with no chance to review it, and a partial or truncated download can execute half a command.",
    safer: "Save the file, read it, verify a published checksum or signature, then execute it deliberately.",
  },
  {
    slug: "dd-to-disk",
    cmd: "dd if=/dev/zero of=/dev/sda bs=1M",
    label: "dd … of=/dev/sda",
    tagline: "Overwrite a raw disk, destroying every partition",
    what: "Copies zeroes block-by-block directly onto the whole disk device /dev/sda, ignoring the filesystem entirely.",
    why: "It obliterates the partition table and all filesystems on the drive with no confirmation — dd is often nicknamed 'disk destroyer'. Point it at the wrong device and the data is gone.",
    safer: "Triple-check the target with `lsblk` first, write to a partition or file rather than the whole disk when you can, and never run dd against a device unless you are certain which one it is.",
  },
  {
    slug: "mkfs-on-disk",
    cmd: "mkfs.ext4 /dev/sda1",
    label: "mkfs.ext4 /dev/sda1",
    tagline: "Create a fresh filesystem, erasing what was there",
    what: "Formats the given partition with a new ext4 filesystem.",
    why: "Formatting discards everything currently stored on that partition. Aim it at a mounted system or data partition and that data is unrecoverable.",
    safer: "Confirm the device is the right, unmounted target with `lsblk`/`blkid`, and make sure you have a backup before formatting anything.",
  },
  {
    slug: "chmod-777-recursive",
    cmd: "chmod -R 777 /",
    label: "chmod -R 777 /",
    tagline: "Make the whole system world-writable",
    what: "Recursively sets read/write/execute permissions for everyone on every file starting at /.",
    why: "It removes the permission boundaries the OS relies on — any user (or process) can modify system binaries and configuration, which is both a severe security hole and enough to stop services like SSH from starting.",
    safer: "Scope permission changes to the specific directory that needs them, and prefer the least-open mode that works (e.g. 755 for directories, 644 for files). Never chmod system roots.",
  },
  {
    slug: "chown-recursive-root",
    cmd: "chown -R nobody:nobody /",
    label: "chown -R … /",
    tagline: "Reassign ownership of the entire tree",
    what: "Recursively changes the owner and group of every file from the root down.",
    why: "System services expect specific owners; rewriting ownership across / can lock root out of files, break sudo, and stop the machine from booting cleanly.",
    safer: "Change ownership only on the exact path that needs it, and back up permission state first (e.g. with `getfacl -R` or a filesystem snapshot).",
  },
  {
    slug: "redirect-to-disk",
    cmd: "echo data > /dev/sda",
    label: "> /dev/sda",
    tagline: "Redirect output straight onto a disk device",
    what: "Sends the output of a command directly into the raw disk device, overwriting the bytes at the start of the drive.",
    why: "Writing to /dev/sda bypasses the filesystem and corrupts the partition table or boot sector, which can make the whole drive unmountable.",
    safer: "Redirect into a normal file path (e.g. > ./out.txt). Only write to a device node when you genuinely intend low-level disk work, and double-check the name.",
  },
  {
    slug: "git-push-force",
    cmd: "git push --force origin main",
    label: "git push --force",
    tagline: "Overwrite shared branch history",
    what: "Replaces the remote branch with your local history, discarding any commits on the remote that you do not have.",
    why: "On a shared branch this can erase teammates' work and rewrite history everyone else has already pulled, causing painful recovery.",
    safer: "Use `git push --force-with-lease`, which refuses to overwrite if the remote has moved since you last fetched, and avoid force-pushing shared branches at all.",
  },
  {
    slug: "git-reset-hard",
    cmd: "git reset --hard HEAD~5",
    label: "git reset --hard",
    tagline: "Throw away uncommitted work and commits",
    what: "Moves the branch pointer back and forcibly resets the working tree, discarding local changes and the intervening commits.",
    why: "Any uncommitted edits are gone with no prompt, and the dropped commits are hard to find later if you did not note their hashes.",
    safer: "Stash or commit first (`git stash` / `git commit`), and prefer `git reset --keep` or a new branch so nothing is silently destroyed. `git reflog` can sometimes recover lost commits.",
  },
  {
    slug: "git-clean-fdx",
    cmd: "git clean -fdx",
    label: "git clean -fdx",
    tagline: "Permanently delete every untracked file",
    what: "Force-removes all untracked files and directories, including ignored ones (-x) like local .env files and build artifacts.",
    why: "It deletes files git is not tracking — often exactly the local secrets, uploads or configs that are not in version control — with no recycle bin.",
    safer: "Dry-run it first with `git clean -nd` to see what would be removed, and drop -x unless you truly want ignored files gone too.",
  },
  {
    slug: "eval-remote",
    cmd: "eval \"$(curl -s https://example.com/env)\"",
    label: "eval \"$(…)\"",
    tagline: "Execute an assembled string as code",
    what: "Runs the captured output of another command as if you had typed it, here feeding a remote response straight into eval.",
    why: "Whatever the substituted text contains becomes live shell code; if any part is attacker-controlled, arbitrary commands run in your shell.",
    safer: "Avoid eval on untrusted input. Capture data into a variable and use it as data, not code, and read remote content before acting on it.",
  },
  {
    slug: "shutdown-now",
    cmd: "sudo shutdown -h now",
    label: "sudo shutdown -h now",
    tagline: "Halt the machine immediately",
    what: "Powers the system off right now, as root, giving logged-in users no warning.",
    why: "Active sessions are killed and unsaved work is lost; on a shared or remote server this can interrupt other people and take services offline.",
    safer: "Schedule with a delay and a message (`sudo shutdown -h +5 'rebooting for maintenance'`), or use `shutdown -c` to cancel — and make sure you are on the right host.",
  },
];
