// cmdxray — curated knowledge base of common commands and their flags.
// Hand-curated for accuracy and readability. Short flags are keyed by their
// single letter (so combined flags like -xzvf resolve per-letter); long flags
// are keyed with their leading "--". Extend freely; keep glosses plain-English.

export interface CommandInfo {
  summary: string;
  flags: Record<string, string>;
  // Subcommands, e.g. git: { commit: "record staged changes", ... }.
  subcommands?: Record<string, string>;
  // Flags that consume the FOLLOWING word as their value (short-letter keys and
  // long "--name" keys). Used to label that word as "value for <flag>".
  takesValue?: string[];
  // Per-subcommand flag overrides. When a subcommand is active, these glosses
  // win over the command-level `flags` (e.g. `docker build -t` = tag, not tty;
  // `kubectl logs -f` = follow, not file). Key = subcommand name.
  subFlags?: Record<string, Record<string, string>>;
  // Per-subcommand value-taking overrides. When a subcommand overrides a flag
  // via `subFlags`, whether that flag consumes the next word is decided here
  // (default: it does NOT). Key = subcommand name.
  subTakesValue?: Record<string, string[]>;
  // Traditional tools (tar, ps) accept a leading flag cluster with NO dash,
  // e.g. `tar czf x.tgz`, `ps aux`. When true, the first bare operand made up
  // entirely of known single-letter flags is expanded letter-by-letter.
  bareFlags?: boolean;
  // Two-level subcommands, e.g. `docker compose up`, `git stash pop`. Keyed by
  // the first subcommand; the second bare word is looked up here.
  subSubcommands?: Record<string, Record<string, string>>;
}

export const DB: Record<string, CommandInfo> = {
  tar: {
    summary: "archive utility — bundle files into (or extract them from) a .tar",
    takesValue: ["f", "C", "--exclude", "--exclude-from", "--strip-components", "-T"],
    bareFlags: true,
    flags: {
      c: "create a new archive",
      x: "extract files from an archive",
      t: "list the contents of an archive",
      r: "append files to the end of an archive",
      u: "append only files newer than the archive copy",
      z: "filter the archive through gzip (.gz)",
      j: "filter the archive through bzip2 (.bz2)",
      J: "filter the archive through xz (.xz)",
      v: "verbose — list each file as it is processed",
      f: "use the next argument as the archive file name",
      C: "change to the given directory first",
      p: "preserve file permissions when extracting",
      h: "follow symlinks — archive the files they point to",
      k: "keep existing files; don't overwrite when extracting",
      "--create": "create a new archive",
      "--extract": "extract files from an archive",
      "--list": "list the contents of an archive",
      "--gzip": "filter the archive through gzip",
      "--bzip2": "filter the archive through bzip2",
      "--xz": "filter the archive through xz",
      "--verbose": "verbose — list each file as it is processed",
      "--file": "use the given archive file",
      "--exclude": "skip files matching this pattern",
      "--exclude-from": "skip files matching patterns read from this file",
      "--exclude-vcs": "skip version-control dirs (.git, .svn, …)",
      "--strip-components": "strip this many leading path parts when extracting",
    },
  },
  grep: {
    summary: "search input for lines matching a pattern",
    takesValue: ["e", "f", "A", "B", "C", "m", "d", "--include", "--exclude", "--exclude-dir", "--include-dir"],
    flags: {
      i: "ignore case when matching",
      v: "invert — show lines that do NOT match",
      r: "search directories recursively",
      R: "search directories recursively, following symlinks",
      n: "prefix each match with its line number",
      l: "print only the names of files with matches",
      L: "print only the names of files with NO match",
      c: "print only a count of matching lines",
      E: "interpret the pattern as an extended regex",
      F: "match fixed strings, not regexes",
      P: "interpret the pattern as a Perl-compatible regex (PCRE)",
      G: "interpret the pattern as a basic regex (the default)",
      o: "print only the matched part of each line",
      w: "match whole words only",
      x: "match only whole lines",
      I: "skip binary files (treat them as non-matching)",
      a: "treat binary files as text",
      H: "print the file name with each match",
      h: "never print the file name with matches",
      q: "quiet — print nothing, exit 0 on the first match",
      s: "suppress error messages about unreadable files",
      z: "treat input and output as NUL-separated lines",
      A: "also print N lines after each match",
      B: "also print N lines before each match",
      C: "also print N lines of context around each match",
      e: "use the next argument as the pattern",
      f: "read patterns from the given file",
      "--ignore-case": "ignore case when matching",
      "--invert-match": "show lines that do NOT match",
      "--recursive": "search directories recursively",
      "--line-number": "prefix each match with its line number",
      "--color": "highlight matches in color",
      "--include": "only search files whose name matches this glob",
      "--exclude": "skip files whose name matches this glob",
      "--exclude-dir": "skip directories whose name matches this glob",
      "--include-dir": "only descend into directories matching this glob",
      "--word-regexp": "match whole words only",
      "--fixed-strings": "match fixed strings, not regexes",
      "--files-with-matches": "print only the names of files with matches",
      "--count": "print only a count of matching lines",
      "--only-matching": "print only the matched part of each line",
      "--extended-regexp": "interpret the pattern as an extended regex",
      "--perl-regexp": "interpret the pattern as a Perl-compatible regex",
      "--quiet": "quiet — print nothing, exit 0 on the first match",
      "--no-filename": "never print the file name with matches",
      "--with-filename": "print the file name with each match",
    },
  },
  ls: {
    summary: "list directory contents",
    flags: {
      l: "long format — permissions, owner, size, date",
      a: "show hidden entries (dotfiles) too",
      A: "show hidden entries except . and ..",
      h: "human-readable sizes (K, M, G)",
      t: "sort by modification time, newest first",
      r: "reverse the sort order",
      S: "sort by file size, largest first",
      R: "list subdirectories recursively",
      d: "list directories themselves, not their contents",
      1: "list one entry per line",
    },
  },
  rm: {
    summary: "remove files or directories",
    flags: {
      r: "recurse into directories (delete their contents)",
      f: "force — ignore missing files, never prompt",
      i: "prompt before every removal",
      v: "verbose — explain what is being done",
      d: "remove empty directories",
    },
  },
  cp: {
    summary: "copy files or directories",
    flags: {
      r: "copy directories recursively",
      R: "copy directories recursively",
      f: "force — overwrite the destination if needed",
      i: "prompt before overwriting",
      p: "preserve mode, ownership and timestamps",
      v: "verbose — print each file as it is copied",
      a: "archive — recursive plus preserve everything",
      u: "copy only when the source is newer than the destination",
    },
  },
  mv: {
    summary: "move or rename files and directories",
    flags: {
      f: "force — overwrite the destination without prompting",
      i: "prompt before overwriting",
      n: "never overwrite an existing file",
      v: "verbose — print each file as it is moved",
    },
  },
  ln: {
    summary: "make links between files",
    flags: {
      s: "make a symbolic (soft) link instead of a hard link",
      f: "force — remove an existing destination first",
      n: "treat a symlinked destination as a normal file",
      v: "verbose — print the name of each linked file",
      r: "make the symlink target relative to the link location",
    },
  },
  mkdir: {
    summary: "create directories",
    flags: {
      p: "create parent directories as needed, no error if they exist",
      v: "print a message for each created directory",
      m: "set the permission mode of the new directory",
    },
  },
  curl: {
    summary: "transfer data to or from a URL",
    takesValue: ["o", "X", "H", "d", "u", "A", "b", "c", "e"],
    flags: {
      s: "silent — hide the progress meter and errors",
      S: "with -s, still show errors",
      L: "follow HTTP redirects",
      o: "write output to the given file",
      O: "save output using the remote file name",
      X: "set the HTTP request method (e.g. POST)",
      H: "add a request header",
      d: "send the given data in a POST body",
      F: "send a multipart/form-data field",
      f: "fail silently on server errors (no error page)",
      k: "allow insecure TLS connections",
      i: "include the response headers in the output",
      I: "fetch only the response headers (HEAD request)",
      u: "supply user:password credentials",
      A: "set the User-Agent header",
      b: "send cookies (string or file)",
      "--silent": "hide the progress meter",
      "--location": "follow HTTP redirects",
      "--output": "write output to the given file",
      "--header": "add a request header",
      "--request": "set the HTTP request method",
      "--data": "send the given data in a POST body",
      "--fail": "fail silently on server errors",
    },
  },
  wget: {
    summary: "download files from the web over HTTP/FTP",
    takesValue: ["O", "P"],
    flags: {
      O: "write the download to the given file name",
      P: "save files into the given directory",
      c: "continue a partially downloaded file",
      q: "quiet — no output",
      r: "recursive — download linked pages too",
      "--no-check-certificate": "skip TLS certificate validation",
    },
  },
  find: {
    summary: "walk a directory tree looking for files",
    takesValue: [
      "-name",
      "-iname",
      "-path",
      "-ipath",
      "-type",
      "-mtime",
      "-mmin",
      "-size",
      "-maxdepth",
      "-mindepth",
      "-newer",
      "-user",
      "-group",
      "-perm",
    ],
    flags: {
      "-name": "match files by this name pattern",
      "-iname": "match by name, case-insensitively",
      "-path": "match by path pattern",
      "-ipath": "match by path pattern, case-insensitively",
      "-type": "match by type (f=file, d=directory, l=symlink)",
      "-mtime": "match by modification age in days",
      "-mmin": "match by modification age in minutes",
      "-size": "match by file size",
      "-newer": "match files newer than the given reference file",
      "-user": "match files owned by this user",
      "-group": "match files owned by this group",
      "-perm": "match files with these permission bits",
      "-empty": "match empty files and directories",
      "-exec": "run a command on each match ({} = the file, ; ends it)",
      "-execdir": "like -exec, but run from the match's own directory",
      "-ok": "like -exec, but prompt before running each command",
      "-okdir": "like -execdir, but prompt before running each command",
      "-delete": "delete each matching file",
      "-prune": "don't descend into a matching directory",
      "-maxdepth": "descend at most this many directory levels",
      "-mindepth": "ignore matches shallower than this many levels",
      "-print": "print each match (the default action)",
      "-print0": "print each match separated by NUL (for xargs -0)",
    },
  },
  ffmpeg: {
    summary: "record, convert and stream audio and video",
    flags: {
      "-i": "read from this input file (repeat for multiple inputs)",
      "-vf": "apply a video filter graph (scale, crop, fps, overlay, …)",
      "-af": "apply an audio filter graph",
      "-filter_complex": "apply a filter graph across multiple inputs/outputs",
      "-c": "set the codec (use -c:v for video, -c:a for audio, copy = remux)",
      "-c:v": "set the video codec (e.g. libx264, libx265)",
      "-c:a": "set the audio codec (e.g. aac, libmp3lame)",
      "-vcodec": "set the video codec (older spelling of -c:v)",
      "-acodec": "set the audio codec (older spelling of -c:a)",
      "-b:v": "set the target video bitrate (e.g. 1M)",
      "-b:a": "set the target audio bitrate (e.g. 128k)",
      "-crf": "constant rate factor — quality vs size (lower = better, x264/x265)",
      "-preset": "encoding speed vs compression trade-off (ultrafast … veryslow)",
      "-r": "set the frame rate in frames per second",
      "-s": "set the frame size as WxH (e.g. 1280x720)",
      "-ss": "seek to this start time before processing",
      "-t": "limit the output to this duration",
      "-to": "stop writing at this timestamp",
      "-map": "choose which input streams end up in the output",
      "-f": "force this container/output format",
      "-an": "drop the audio stream (no audio)",
      "-vn": "drop the video stream (no video)",
      "-sn": "drop the subtitle stream",
      "-y": "overwrite the output file without asking",
      "-n": "never overwrite an existing output file",
      "-loglevel": "set how verbose ffmpeg's logging is",
      "-hide_banner": "suppress the startup copyright/build banner",
    },
    takesValue: [
      "-i", "-vf", "-af", "-filter_complex", "-c", "-c:v", "-c:a", "-vcodec",
      "-acodec", "-b:v", "-b:a", "-crf", "-preset", "-r", "-s", "-ss", "-t",
      "-to", "-map", "-f", "-loglevel",
    ],
  },
  openssl: {
    summary: "OpenSSL — command-line cryptography and TLS toolkit",
    subcommands: {
      req: "create or process a certificate signing request (CSR)",
      x509: "display or convert an X.509 certificate",
      genrsa: "generate an RSA private key",
      genpkey: "generate a private key (any algorithm)",
      rsa: "inspect or convert an RSA key",
      pkey: "inspect or convert a private key",
      s_client: "open a TLS connection to a server (debugging client)",
      s_server: "run a simple TLS server",
      dgst: "compute a message digest (hash) or sign/verify",
      enc: "symmetric-cipher encrypt or decrypt",
      rand: "generate random bytes",
      verify: "verify a certificate chain",
      pkcs12: "build or parse a PKCS#12 (.p12/.pfx) bundle",
    },
    flags: {
      "-x509": "output a self-signed certificate instead of a CSR",
      "-new": "generate a new request/key",
      "-newkey": "generate a new key of this type (e.g. rsa:4096)",
      "-key": "use this existing private key",
      "-keyout": "write the generated private key to this file",
      "-out": "write output to this file",
      "-in": "read input from this file",
      "-days": "how many days the certificate stays valid",
      "-nodes": "don't encrypt the private key (no passphrase)",
      "-subj": "set the subject DN inline (skip the interactive prompts)",
      "-sha256": "use SHA-256 as the signature/digest algorithm",
      "-text": "also print the certificate/key in human-readable text",
      "-noout": "don't print the encoded (PEM/DER) output",
      "-config": "use this OpenSSL configuration file",
      "-connect": "host:port to connect to (s_client)",
      "-servername": "SNI hostname to send (s_client)",
      "-passin": "source of the input passphrase",
      "-passout": "source of the output passphrase",
    },
    takesValue: [
      "-newkey", "-key", "-keyout", "-out", "-in", "-days", "-subj",
      "-config", "-connect", "-servername", "-passin", "-passout",
    ],
  },
  chmod: {
    summary: "change file mode (permission) bits",
    flags: {
      R: "apply changes recursively",
      v: "verbose — report each change",
      c: "report only files that actually change",
      f: "suppress error messages",
    },
  },
  chown: {
    summary: "change file owner and group",
    flags: {
      R: "apply changes recursively",
      v: "verbose — report each change",
      h: "affect symlinks themselves, not their targets",
    },
  },
  ssh: {
    summary: "log in to or run a command on a remote machine",
    takesValue: ["i", "p", "L", "R", "o"],
    flags: {
      i: "use the given private key file",
      p: "connect to this port",
      L: "set up local port forwarding",
      R: "set up remote port forwarding",
      D: "set up a local SOCKS proxy (dynamic forwarding)",
      N: "do not run a remote command (forwarding only)",
      f: "go to the background after authenticating",
      v: "verbose — print debugging output",
      t: "force a pseudo-terminal",
      o: "set an ssh_config option (e.g. StrictHostKeyChecking=no)",
    },
  },
  scp: {
    summary: "copy files between hosts over SSH",
    takesValue: ["i", "P"],
    flags: {
      r: "copy directories recursively",
      P: "connect to this port (capital P, unlike ssh)",
      i: "use the given private key file",
      p: "preserve modification times and modes",
      C: "compress data during transfer",
    },
  },
  rsync: {
    summary: "efficiently sync files, copying only what changed",
    takesValue: ["e"],
    flags: {
      a: "archive — recurse and preserve nearly everything",
      v: "verbose — list files as they transfer",
      z: "compress data during transfer",
      r: "recurse into directories",
      P: "show progress and keep partial files",
      n: "dry run — show what would happen, change nothing",
      u: "skip files that are newer on the destination",
      e: "use the given remote shell (e.g. ssh)",
      "--delete": "delete files on the destination that are gone from the source",
      "--exclude": "skip files matching this pattern",
      "--progress": "show a progress bar during transfer",
      "--dry-run": "show what would happen, change nothing",
    },
  },
  docker: {
    summary: "build, run and manage containers",
    takesValue: ["p", "v", "e", "--name", "--network", "-w"],
    subcommands: {
      run: "create and start a new container",
      build: "build an image from a Dockerfile",
      ps: "list running containers",
      images: "list local images",
      exec: "run a command inside a running container",
      pull: "download an image from a registry",
      push: "upload an image to a registry",
      stop: "stop a running container",
      rm: "remove a container",
      rmi: "remove an image",
      logs: "show a container's output",
      compose: "run multi-container apps from a compose file",
    },
    subFlags: {
      build: { t: "tag the built image (name:tag)" },
      compose: {
        d: "detached — run the services in the background",
        "--build": "build images before starting the containers",
        "--no-cache": "don't use cache when building images",
        "--force-recreate": "recreate containers even if config is unchanged",
        "--remove-orphans": "remove containers for services not in the compose file",
        "-f": "use the given compose file",
      },
    },
    subTakesValue: {
      build: ["t"],
      compose: ["-f"],
    },
    subSubcommands: {
      compose: {
        up: "create and start the services in the compose file",
        down: "stop and remove the services, networks and volumes",
        build: "build or rebuild the services' images",
        ps: "list the compose project's containers",
        logs: "show output from the services",
        exec: "run a command in a running service container",
        run: "run a one-off command against a service",
        start: "start existing service containers",
        stop: "stop running service containers",
        restart: "restart service containers",
        pull: "pull the services' images",
        config: "validate and print the resolved compose file",
      },
    },
    flags: {
      d: "detached — run in the background",
      it: "interactive with a terminal attached",
      i: "keep STDIN open (interactive)",
      t: "allocate a pseudo-terminal",
      p: "publish a container port to the host (host:container)",
      v: "mount a volume (host path : container path)",
      e: "set an environment variable",
      w: "set the working directory inside the container",
      "--rm": "remove the container when it exits",
      "--name": "give the container a name",
      "--network": "connect the container to this network",
    },
  },
  git: {
    summary: "the distributed version control system",
    takesValue: ["-C", "m", "b"],
    subFlags: {
      log: { n: "limit output to the last N commits" },
      shortlog: { n: "sort authors by number of commits" },
      commit: { n: "skip the pre-commit and commit-msg hooks (--no-verify)" },
      rebase: { i: "interactive — edit the list of commits before replaying them" },
    },
    subTakesValue: {
      log: ["n"],
    },
    subcommands: {
      clone: "copy a repository to your machine",
      init: "create a new empty repository here",
      add: "stage changes for the next commit",
      commit: "record staged changes as a new commit",
      status: "show what is staged, modified and untracked",
      push: "upload your commits to a remote",
      pull: "fetch from a remote and merge into the current branch",
      fetch: "download objects and refs from a remote (no merge)",
      checkout: "switch branches or restore files",
      switch: "switch to another branch",
      branch: "list, create or delete branches",
      merge: "join another branch's history into this one",
      rebase: "reapply your commits on top of another base",
      log: "show the commit history",
      diff: "show changes between commits, branches or the working tree",
      stash: "shelve uncommitted changes for later",
      reset: "move the current branch and optionally the index/working tree",
      revert: "make a new commit that undoes an earlier one",
      tag: "create, list or delete tags",
      remote: "manage the set of tracked repositories",
      cherry: "apply the change introduced by a specific commit",
      restore: "restore working-tree files",
    },
    flags: {
      m: "use the next argument as the commit message",
      a: "automatically stage every tracked, modified file",
      b: "create and switch to a new branch",
      f: "force the operation",
      d: "delete (e.g. a branch)",
      D: "force-delete (e.g. an unmerged branch)",
      n: "dry run / no-commit, depending on the subcommand",
      "--amend": "replace the previous commit instead of adding a new one",
      "--force": "force the operation (e.g. push)",
      "--force-with-lease": "force-push only if the remote hasn't moved since you fetched",
      "--all": "operate on everything (all branches / all changes)",
      "--oneline": "show each commit on a single line",
      "--graph": "draw an ASCII graph of the branch structure",
      "--continue": "resume the operation after resolving conflicts",
      "--abort": "cancel the operation and restore the original state",
      "--skip": "skip the current commit and continue",
      "--interactive": "interactive — edit the list of commits before replaying them",
      "--set-upstream": "record this remote branch as the upstream for tracking",
      "--no-verify": "skip the pre-commit and commit-msg hooks",
      "-C": "run as if git was started in the given directory",
    },
  },
  npm: {
    summary: "the Node.js package manager",
    subcommands: {
      install: "install dependencies (or a named package)",
      i: "install dependencies (short for install)",
      run: "run a script defined in package.json",
      test: "run the project's test script",
      start: "run the project's start script",
      publish: "publish the package to the registry",
      init: "create a package.json",
      update: "update packages to newer allowed versions",
      uninstall: "remove a package",
      ci: "clean install exactly from the lockfile",
      exec: "run a package's binary",
    },
    flags: {
      g: "operate globally, not on the local project",
      D: "save to devDependencies",
      "--save-dev": "save to devDependencies",
      "--global": "operate globally",
      "--production": "skip devDependencies",
    },
  },
  systemctl: {
    summary: "control the systemd init system and its services",
    subcommands: {
      start: "start a service now",
      stop: "stop a running service now",
      restart: "stop and start a service",
      reload: "tell a service to reload its configuration",
      status: "show whether a service is running, plus recent logs",
      enable: "start this service automatically at boot",
      disable: "do not start this service at boot",
      "daemon-reload": "reload systemd's own unit files after edits",
      list: "list units",
      "is-active": "check whether a unit is currently running",
    },
    flags: {
      "--now": "also start/stop immediately (with enable/disable)",
      "--user": "act on the per-user systemd, not the system one",
      "--failed": "limit output to failed units",
    },
  },
  journalctl: {
    summary: "query and display logs from the systemd journal",
    takesValue: [
      "u",
      "--unit",
      "--since",
      "--until",
      "-p",
      "--priority",
      "-n",
      "--lines",
      "-t",
      "--identifier",
      "--user-unit",
      "-b",
      "--boot",
    ],
    flags: {
      u: "show logs for this systemd unit only",
      "--unit": "show logs for this systemd unit only",
      "--user-unit": "show logs for this per-user unit only",
      f: "follow — keep printing new log entries as they arrive",
      "--follow": "follow — keep printing new log entries as they arrive",
      "--since": "only entries at or after this time (e.g. \"1 hour ago\")",
      "--until": "only entries at or before this time",
      n: "show only the last N lines",
      "--lines": "show only the last N lines",
      e: "jump to the end of the journal in the pager",
      "--pager-end": "jump to the end of the journal in the pager",
      r: "reverse — show newest entries first",
      "--reverse": "reverse — show newest entries first",
      k: "show only kernel messages",
      "--dmesg": "show only kernel messages",
      b: "show logs from a specific boot (default: current boot)",
      "--boot": "show logs from a specific boot (default: current boot)",
      x: "add explanatory help text to log messages where available",
      "--catalog": "add explanatory help text to log messages where available",
      p: "filter by priority (e.g. err, warning, or 0-7)",
      "--priority": "filter by priority (e.g. err, warning, or 0-7)",
      "--no-pager": "print straight to the terminal, don't use a pager",
      "--system": "show messages from system services and the kernel",
      "--user": "show messages from the current user's services",
      o: "set the output format (short, json, cat, …)",
      "--output": "set the output format (short, json, cat, …)",
    },
  },
  aws: {
    summary: "command-line interface for Amazon Web Services",
    subcommands: {
      s3: "high-level Amazon S3 object-storage commands (cp, sync, ls, rm…)",
      s3api: "low-level, 1:1 mapping to the S3 API",
      ec2: "manage EC2 virtual machines, volumes, security groups…",
      iam: "manage IAM users, roles, and permissions",
      lambda: "manage AWS Lambda serverless functions",
      logs: "CloudWatch Logs — view and query log groups",
      sts: "Security Token Service — assume roles, get caller identity",
      ecr: "Elastic Container Registry commands",
      eks: "manage Elastic Kubernetes Service clusters",
      configure: "set up credentials, region, and output defaults",
      dynamodb: "manage DynamoDB tables and items",
      ssm: "Systems Manager — parameters, session manager, run command",
    },
    subSubcommands: {
      s3: {
        cp: "copy files/objects to, from, or between S3",
        sync: "sync a directory tree to/from S3 (only changed files)",
        ls: "list buckets or objects",
        rm: "delete objects",
        mv: "move (copy then delete) objects",
        mb: "make (create) a bucket",
        rb: "remove (delete) a bucket",
      },
    },
    takesValue: [
      "--region",
      "--profile",
      "--output",
      "--acl",
      "--query",
      "--endpoint-url",
      "--sse",
      "--storage-class",
    ],
    flags: {
      "--recursive": "apply the command to all objects under the prefix/directory",
      "--acl": "set a canned access-control policy (e.g. public-read, private)",
      "--dryrun": "show what would happen without actually doing it",
      "--delete": "with sync: delete destination files missing from the source",
      "--exclude": "skip paths matching this pattern",
      "--include": "re-include paths (after --exclude) matching this pattern",
      "--profile": "use this named credentials profile",
      "--region": "target this AWS region",
      "--output": "output format: json, text, table, or yaml",
      "--query": "filter/reshape the output with a JMESPath expression",
      "--no-paginate": "return all results in one response, don't paginate",
      "--endpoint-url": "talk to this endpoint (e.g. an S3-compatible service)",
      "--sse": "server-side-encrypt uploaded objects",
      "--storage-class": "S3 storage class (STANDARD, GLACIER, …)",
      "--version": "print the aws CLI version",
    },
  },
  kubectl: {
    summary: "control a Kubernetes cluster",
    takesValue: ["n", "-n", "o", "-o", "f", "-f", "l", "-l"],
    subcommands: {
      get: "list resources of a given type",
      describe: "show detailed state of a resource",
      apply: "create or update resources from a file",
      delete: "remove resources",
      logs: "print a pod's logs",
      exec: "run a command inside a pod",
      create: "create a resource",
      edit: "edit a live resource in your editor",
      scale: "change the number of replicas",
      rollout: "manage a rollout (status, undo, restart)",
      port: "forward a local port to a pod (port-forward)",
    },
    subFlags: {
      logs: { f: "follow — stream new log lines as they arrive" },
      "port-forward": { f: "read the resource definition from this file" },
    },
    subTakesValue: {
      logs: [],
    },
    flags: {
      n: "act in the given namespace",
      o: "choose the output format (json, yaml, wide)",
      f: "read the resource definition from this file",
      l: "select resources by label",
      w: "watch for changes and stream updates",
      A: "act across all namespaces",
      "--all-namespaces": "act across all namespaces",
      "--namespace": "act in the given namespace",
    },
  },
  apt: {
    summary: "install and manage Debian/Ubuntu packages",
    subcommands: {
      install: "install one or more packages",
      remove: "remove packages but keep their config",
      purge: "remove packages and their config",
      update: "refresh the list of available packages",
      upgrade: "install newer versions of installed packages",
      search: "search for packages by keyword",
      show: "show details about a package",
      list: "list packages (installed, upgradable, …)",
      autoremove: "remove packages no longer needed",
    },
    flags: {
      y: "assume yes — do not prompt for confirmation",
      "--yes": "assume yes — do not prompt for confirmation",
      "--no-install-recommends": "do not install recommended extras",
    },
  },
  sed: {
    summary: "stream editor — transform text line by line",
    takesValue: ["e", "f"],
    flags: {
      i: "edit files in place instead of printing to stdout",
      n: "suppress automatic printing (use with p)",
      e: "add the next argument as an editing script",
      E: "use extended regular expressions",
      r: "use extended regular expressions (GNU)",
      "--in-place": "edit files in place",
    },
  },
  awk: {
    summary: "pattern-scanning and text-processing language",
    takesValue: ["F", "v", "f"],
    flags: {
      F: "set the input field separator",
      v: "assign a variable before the program runs",
      f: "read the awk program from a file",
    },
  },
  jq: {
    summary: "command-line JSON processor (apply a filter to JSON input)",
    takesValue: ["arg", "argjson", "f", "slurpfile", "rawfile"],
    flags: {
      r: "raw output — print strings without JSON quotes",
      j: "raw output with no trailing newline between results",
      c: "compact output — one JSON result per line",
      n: "don't read input; use null as the input",
      s: "slurp — read the whole input stream into one array",
      R: "read raw input — each line becomes a JSON string",
      e: "set the exit code from the last output (for scripting)",
      S: "sort object keys in the output",
      a: "output non-ASCII characters as \\uXXXX escapes",
      f: "read the filter program from a file",
      arg: "define a string variable: --arg name value",
      argjson: "define a JSON variable: --argjson name json",
      tab: "indent the output with tabs",
    },
  },
  ps: {
    summary: "report a snapshot of running processes",
    bareFlags: true,
    flags: {
      a: "show processes for all users",
      u: "show a user-oriented, detailed format",
      x: "include processes without a controlling terminal",
      e: "show every process",
      f: "full-format listing",
    },
  },
  netstat: {
    summary: "show network connections, routing tables, and interface stats",
    flags: {
      t: "TCP connections",
      u: "UDP connections",
      l: "only listening sockets",
      p: "show the PID and program name for each socket",
      n: "numeric output — don't resolve hosts, ports, or users",
      a: "all sockets (listening and non-listening)",
      r: "show the kernel routing table",
      e: "extended information",
      s: "per-protocol summary statistics",
      c: "continuously refresh the display",
    },
  },
  ss: {
    summary: "inspect sockets (a faster, modern replacement for netstat)",
    flags: {
      t: "TCP sockets",
      u: "UDP sockets",
      l: "only listening sockets",
      p: "show the process using each socket",
      n: "numeric output — don't resolve service names",
      a: "all sockets (listening and non-listening)",
      s: "print summary statistics",
    },
  },
  kill: {
    summary: "send a signal to a process",
    flags: {
      "9": "SIGKILL — force the process to stop immediately",
      "15": "SIGTERM — politely ask the process to stop",
      l: "list the available signal names",
      s: "send the named signal",
    },
  },
  xargs: {
    summary: "build and run command lines from standard input",
    takesValue: ["n", "I", "P", "d"],
    flags: {
      n: "use at most this many arguments per command",
      I: "replace this token with each input item",
      "0": "input items are separated by NUL, not whitespace",
      P: "run this many commands in parallel",
      r: "do nothing if the input is empty",
      t: "print each command before running it",
    },
  },
  head: {
    summary: "print the first part of files",
    takesValue: ["n", "c"],
    flags: {
      n: "print the first N lines",
      c: "print the first N bytes",
    },
  },
  tail: {
    summary: "print the last part of files",
    takesValue: ["n", "c"],
    flags: {
      n: "print the last N lines",
      c: "print the last N bytes",
      f: "follow — keep printing new lines as the file grows",
      F: "follow by name, retrying if the file is rotated",
    },
  },
  sort: {
    summary: "sort lines of text",
    takesValue: ["k", "t"],
    flags: {
      n: "sort numerically, not alphabetically",
      r: "reverse the result order",
      u: "output only the first of equal lines (unique)",
      h: "sort human-readable sizes (2K, 1G)",
      k: "sort by the given field/key",
      t: "use the given field separator",
      f: "fold case — treat lower and upper case alike",
    },
  },
  cut: {
    summary: "extract selected columns from each line",
    takesValue: ["d", "f", "c"],
    flags: {
      d: "use the given delimiter between fields",
      f: "select these fields",
      c: "select these character positions",
    },
  },
  tr: {
    summary: "translate or delete characters",
    flags: {
      d: "delete the given characters",
      s: "squeeze repeats of the given characters into one",
      c: "use the complement of the given set",
    },
  },
  wc: {
    summary: "count lines, words and bytes",
    flags: {
      l: "count lines",
      w: "count words",
      c: "count bytes",
      m: "count characters",
    },
  },
  cat: {
    summary: "concatenate files and print them",
    flags: {
      n: "number every output line",
      A: "show non-printing characters, tabs and line ends",
      b: "number non-blank output lines",
    },
  },
  du: {
    summary: "estimate file and directory disk usage",
    takesValue: ["-max-depth"],
    flags: {
      h: "human-readable sizes (K, M, G)",
      s: "show only a total for each argument",
      a: "show sizes for files too, not just directories",
      c: "also print a grand total",
      "-max-depth": "only report directories this many levels deep",
    },
  },
  df: {
    summary: "report free space on mounted filesystems",
    flags: {
      h: "human-readable sizes (K, M, G)",
      T: "also show each filesystem's type",
      i: "report inode usage instead of block usage",
    },
  },
  ping: {
    summary: "test reachability of a host on the network",
    takesValue: ["c", "i", "W"],
    flags: {
      c: "stop after sending this many packets",
      i: "wait this many seconds between packets",
      W: "time to wait for a reply, in seconds",
    },
  },
  dd: {
    summary: "copy and convert data block by block",
    flags: {
      "if": "read from this input file",
      of: "write to this output file",
      bs: "read and write this many bytes at a time",
      count: "copy only this many blocks",
      status: "control how progress is reported",
    },
  },
  make: {
    summary: "build targets according to a Makefile",
    takesValue: ["j", "f", "C"],
    flags: {
      j: "run this many recipe jobs in parallel",
      f: "use the given file instead of Makefile",
      C: "change to this directory first",
      B: "unconditionally rebuild every target",
      n: "dry run — print recipes without running them",
    },
  },
};

// Generic hints for very common flags on unknown commands.
export const GENERIC_FLAGS: Record<string, string> = {
  h: "usually: show help / human-readable output",
  v: "usually: verbose output (or print the version)",
  f: "usually: force, or read from a file",
  r: "usually: recurse into directories",
  o: "usually: write output to a file",
  q: "usually: quiet — suppress normal output",
  y: "usually: assume yes to prompts",
  n: "usually: dry run, or a count",
  "--help": "show usage information and exit",
  "--version": "print the version and exit",
  "--verbose": "produce more detailed output",
  "--quiet": "suppress normal output",
  "--force": "proceed without prompting",
  "--yes": "assume yes to prompts",
  "--dry-run": "show what would happen without doing it",
};

// Representative "positive-control" invocations, one or more per command.
// These pin real behaviour so a regression in parsing/flag-resolution for any
// program is caught immediately (see test/positive-controls.test.js). When you
// add a command to DB above, add at least one example here — the test suite
// fails otherwise, keeping coverage in lock-step with the knowledge base.
export const EXAMPLES: Record<string, string[]> = {
  tar: ["tar -xzvf archive.tar.gz", "tar czf backup.tgz src"],
  grep: ["grep -rn TODO src", "grep -i --color needle file.txt"],
  ls: ["ls -la", "ls -lhSr"],
  rm: ["rm -rf build", "rm -i note.txt"],
  cp: ["cp -r src dest", "cp -p a.txt b.txt"],
  mv: ["mv -i old new", "mv -v a b"],
  mkdir: ["mkdir -p a/b/c", "mkdir -m 755 dir"],
  ln: ["ln -s /usr/bin/python3 python", "ln -sf target link"],
  curl: ["curl -sSL -o out.html https://example.com", "curl -X POST -H 'A: b' -d data url"],
  wget: ["wget -c -O file.zip https://example.com/f.zip"],
  find: ["find . -name '*.log' -mtime +30 -delete", "find src -type f -maxdepth 2"],
  ffmpeg: ["ffmpeg -i in.mov -c:v libx264 -crf 23 -preset medium out.mp4", "ffmpeg -i in.mp4 -vf scale=1280:-1 -an out.webm"],
  openssl: ["openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes", "openssl s_client -connect example.com:443 -servername example.com"],
  chmod: ["chmod -R 755 dir", "chmod -v 600 key"],
  chown: ["chown -R user:group dir"],
  ssh: ["ssh -i key.pem -p 2222 user@host", "ssh -N -L 8080:localhost:80 host"],
  scp: ["scp -r -P 22 file user@host:/tmp"],
  rsync: ["rsync -avz --delete src/ dest/", "rsync -a --dry-run a/ b/"],
  docker: ["docker run -it --rm -p 8080:80 nginx", "docker build -t myimg ."],
  git: ["git commit -am 'fix bug'", "git checkout -b feature", "git log --oneline --graph"],
  npm: ["npm install -D typescript", "npm run build"],
  systemctl: ["systemctl restart nginx", "systemctl enable --now docker"],
  journalctl: ["journalctl -u nginx --since \"1 hour ago\" -f", "journalctl -xe -p err"],
  aws: ["aws s3 cp ./dist s3://mybucket/ --recursive --acl public-read", "aws s3 sync . s3://bucket --delete"],
  kubectl: ["kubectl get pods -n default -o wide", "kubectl logs -f mypod"],
  apt: ["apt install -y curl", "apt upgrade --yes"],
  sed: ["sed -i 's/a/b/g' file.txt", "sed -n -e '1,10p' file.txt"],
  awk: ["awk -F, '{print $1}' data.csv"],
  jq: ["jq -r '.items[] | select(.age > 30) | .name' data.json"],
  ps: ["ps aux", "ps -ef"],
  netstat: ["netstat -tulpn", "netstat -rn"],
  ss: ["ss -tulpn", "ss -s"],
  kill: ["kill -9 1234", "kill -15 4321"],
  xargs: ["xargs -0 -I{} rm {}", "xargs -n1 -P4 echo"],
  head: ["head -n 20 file.txt", "head -c 100 file.bin"],
  tail: ["tail -f -n 100 log.txt"],
  sort: ["sort -k2 -n -r data.txt", "sort -u -f names.txt"],
  cut: ["cut -d, -f1 data.csv", "cut -c1-10 file.txt"],
  tr: ["tr -d '\\n'", "tr -s ' '"],
  wc: ["wc -l file.txt", "wc -w -c file.txt"],
  cat: ["cat -n file.txt", "cat -A file.txt"],
  du: ["du -sh dir", "du -ah ."],
  df: ["df -h", "df -T -i"],
  ping: ["ping -c 4 host", "ping -i 2 host"],
  dd: ["dd if=/dev/zero of=out.img bs=1M count=10"],
  make: ["make -j4 -C build", "make -f Makefile.dev -n"],
};
